package net.jacobpeterson.jet.openapiannotations.annotation.meta;

import net.jacobpeterson.jet.openapiannotations.OpenApiAnnotationsProcessor;
import org.jspecify.annotations.NullMarked;

/**
 * {@link AnnotationsValidationLevel} is an enum for the validation level of the OpenAPI specification JSON outputs
 * generated by {@link OpenApiAnnotationsProcessor} from OpenAPI annotations.
 */
@NullMarked
public enum AnnotationsValidationLevel {

    /**
     * Do not perform any validation of the OpenAPI specification JSON output.
     */
    NONE,

    /**
     * Perform validation of the OpenAPI specification JSON output and reports schema offenses as warnings.
     */
    WARNING,

    /**
     * Perform validation of the OpenAPI specification JSON output and reports schema offenses as errors.
     */
    ERROR
}
