const val JET_GROUP = "net.jacobpeterson.jet"
const val JET_VERSION = "1.0.1"
const val GITHUB_PROJECT_URL = "https://github.com/Petersoj/jet"
const val JRELEASER_MAVEN_NAME = "jreleaser"
const val JRELEASER_MAVEN_REPOSITORY_DIRECTORY = "jreleaser-staging"
